# === NFS Client

nfs_client_packages:
  - glusterfs-client
  - glusterfs-common
  - glusterfs-server

nfsclient_autofs_glusterfs_server: localhost
nfsclient_autofs_glusterfs_backup_server: lnls449-linux
nfsclient_autofs_glusterfs_log_file: /var/log/gluster.log

# autofs: auto.sirius
nfsclient_autofs_extra:
  - |
    /home/sirius/shared -fstype=glusterfs,backupvolfile-server={{ nfsclient_autofs_glusterfs_backup_server }},log-level=WARNING,log-file={{ nfsclient_autofs_glusterfs_log_file }},rw {{ nfsclient_autofs_glusterfs_server }}:/shared

