---
galaxy_info:
  author: Ximenes Resende
  description: Ansible role to install control system constants in servweb
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
