---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Define CS Studio dependency packages
  set_fact:
    csstudio_dep_packages: "{{ __csstudio_dep_packages | default ([]) }}"
  when: csstudio_dep_packages is not defined

- name: Define Java 8 install
  set_fact:
    csstudio_install_oracle_java: "{{ __csstudio_install_oracle_java | default (false) }}"
  when: csstudio_install_oracle_java is not defined

- name: Define Java oracle 8 keyservers/keys
  set_fact:
    csstudio_repository_keys: "{{ __csstudio_repository_keys | default ([]) }}"
  when: csstudio_repository_keys is not defined

- name: Define Java oracle 8 repositories
  set_fact:
    csstudio_repository_apt: "{{ __csstudio_repository_apt | default ([]) }}"
  when: csstudio_repository_apt is not defined

- name: Define Java oracle packages
  set_fact:
    csstudio_oracle_java_packages: "{{ __csstudio_oracle_java_packages | default ([]) }}"
  when: csstudio_oracle_java_packages is not defined

- name: Define Java hold packages
  set_fact:
    csstudio_deb_java_hold_packages: "{{ __csstudio_deb_java_hold_packages | default ([]) }}"
  when: csstudio_deb_java_hold_packages is not defined

- name: Debug
  debug:
    msg: "csstudio_base_url: {{ csstudio_base_url }}"

- name: Debug
  debug:
    msg: "pkg_version_ntp: {{ pkg_version_ntp }}"

# Setup/install tasks
- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- include_tasks: install-oracle-java.yml
  when:
    - csstudio_install_oracle_java

- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: setup-cs-studio.yml
