---
vars:
  apt_proxy_server: "${APT_PROXY_SERVER}"

dependency:
  name: galaxy
  collections:
    - name: community.docker
      version: 1.5.0
  options:
    role-file: requirements.yml
    collection-file: requirements.yml

driver:
  name: docker

lint: |
  set -x
  yamllint .
  ansible-lint

platforms:
  - name: lnls-ans-role-clone-install
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    command: ${MOLECULE_DOCKER_COMMAND:-'bash -c "while true; do sleep 10000; done"'}
    groups:
      - default_group
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    build_image: false
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
    group_vars:
      default_group:

verifier:
  name: ansible
