---
- hosts: ioc_servers
  remote_user: sirius
  become: true

  roles:
    - role: lnls-ans-role-repositories
    - role: lnls-ans-role-users
      when: global_repositories_role | default(true) | bool
    - role: lnls-ans-role-ntp
    - role: lnls-ans-role-python
    - role: lnls-ans-role-epics
    - role: lnls-ans-role-epics7
    - role: lnls-ans-role-sirius-apps
