---
- hosts: docker_servers
  remote_user: server
  become: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "group_vars/{{ ansible_distribution }}.yml"
          - "group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Create docker certs.d/ for the internal registry
      file:
        path: "/etc/docker/certs.d/{{ docker_registry_server }}/"
        state: directory
        mode: "0755"

    - name: Copy self signed crt to the client machine
      ansible.posix.synchronize:
        src: "{{ docker_registry_ssl_crt_path }}"
        dest: "/etc/docker/certs.d/{{ docker_registry_server }}/ca.crt"
      delegate_to: "{{ docker_registry_server }}"
