---
- hosts: bbb
  remote_user: fac
  become: true
  tasks:
    - git:
        repo: 'https://github.com/lnls-sirius/eth-bridge-pru-serial485'
        dest: /root/eth-bridge-pru-serial485
        version: "{{ pkg_version_ethbridge_pru_serial }}"
