---
- hosts: control_room:linac_opi:fac_control_room:fac_servers:con:elp:control_room_LEGACY
  remote_user: sirius
  become: true

  tasks:
    - name: Include generic desktop tasks
      include_tasks: tasks-desktops.yml
