---
- hosts: control_room:control_room_tv:linac_opi:control_room_nvidia_false
  remote_user: sirius
  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "group_vars/{{ ansible_distribution }}.yml"
          - "group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

  tasks:
    - name: "Gluster packages"
      apt:
        name: "{{ item }}"
      loop:
        - glusterfs-client
        - glusterfs-common
        - glusterfs-server

    - name: "Create gluster brick directory"
      file:
        path: /data/gluster/shared-brick
        state: directory
        mode: "0755"

    - name: "Create common volume mount point directory"
      file:
        path: /home/sirius/shared
        state: directory
        mode: "0755"

    - name: "Gluster Service"
      ansible.builtin.service:
        name: glusterd
        state: started
        enabled: yes

