---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install EPICS base and extra packages
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.6

  platforms:
    - name: Debian
      versions:
        - buster
        - stretch
        - jessie
    - name: Ubuntu
      versions:
        - xenial
        - trusty
  galaxy_tags:
    - development
    - epics
    - system

dependencies:
#  - lnls-ans-role-octave
#  - lnls-ans-role-epics
