---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
    group_vars:
      default_group:
  options:
    extra_vars:
      qt_src_remote_script: "qt-opensource-linux-x64-{{ qt_src_version }}.run"
      qt_src_download_url: "https://download.qt.io/archive/qt/{{ qt_src_version_reduced }}/{{ qt_src_version }}/{{ qt_src_remote_script }}"
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
platforms:
  - name: lnls-ans-role-qt-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
