---
__epics_packages:
  - epics-dev={{ pkg_version_epics_dev }}
  - epics-pcas-dev={{ pkg_version_epics_pcas_dev }}

__epics_pip_packages:
  - pyepics
  - pcaspy

__pip_executable: pip-sirius

__pip2_executable: pip
