---
# Define list of paths + permissions to be exported, such as:
# nfsserver_exports: [ "/home/public *(rw,sync,no_root_squash)" ]
nfsserver_exports: []

# Set this to true when using this in a regular,
# without systemd support.
nfs_ignore_systemd_errors: false

nfs_config_files:
  - name: NFS server exports file
    filename: exports
    pathname: "/etc"
