---
nfs_clients_auto_backup_ta_ti_rack_ip: ""
nfs_clients_auto_backup_ca_ra_ctrl_ip: ""
nfs_clients_auto_backup_la_ra_ctrl_ip: ""
nfs_clients_servers_subnet: ""
nfs_clients_cons_subnet: ""
nfs_clients_control_room_subnet: ""
nfs_clients_cnpem_sirius_subnet: ""
fac_workstation_ip: ""

# Set this to true when using this in a regular,
# without systemd support.
nfs_ignore_systemd_errors: false

nfs_config_files:
  - name: NFS server exports file
    filename: exports
    pathname: "/etc"
