---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Define NFS server packages
  set_fact:
    nfs_server_packages: "{{ __nfs_server_packages | default ([]) }}"
  when: nfs_server_packages is not defined

- name: Check if NFS auto backup TA-TiRack variable is set
  fail:
    msg: nfs_clients_auto_backup_ta_ti_rack_ip variable is not set or empty!
  when: >
    nfs_clients_auto_backup_ta_ti_rack_ip is not defined or
    nfs_clients_auto_backup_ta_ti_rack_ip | length == 0

- name: Check if NFS auto backup CA-RaCtrl variable is set
  fail:
    msg: nfs_clients_auto_backup_ca_ra_ctrl_ip variable is not set or empty!
  when: >
    nfs_clients_auto_backup_ca_ra_ctrl_ip is not defined or
    nfs_clients_auto_backup_ca_ra_ctrl_ip | length == 0

- name: Check if NFS auto backup LA-RaCtrl variable is set
  fail:
    msg: nfs_clients_auto_backup_la_ra_ctrl_ip variable is not set or empty!
  when: >
    nfs_clients_auto_backup_la_ra_ctrl_ip is not defined or
    nfs_clients_auto_backup_la_ra_ctrl_ip | length == 0

- name: Check if NFS servers variable is set
  fail:
    msg: nfs_clients_servers_subnet variable is not set or empty!
  when: >
    nfs_clients_servers_subnet is not defined or
    nfs_clients_servers_subnet | length == 0

- name: Check if NFS CONs subnet variable is set
  fail:
    msg: nfs_clients_cons_subnet variable is not set or empty!
  when: >
    nfs_clients_cons_subnet is not defined or
    nfs_clients_cons_subnet | length == 0

- name: Check if NFS control room subnet variable is set
  fail:
    msg: nfs_clients_control_room_subnet variable is not set or empty!
  when: >
    nfs_clients_control_room_subnet is not defined or
    nfs_clients_control_room_subnet | length == 0

- name: Check if NFS CNPEM Sirius subnet variable is set
  fail:
    msg: nfs_clients_cnpem_sirius_subnet variable is not set or empty!
  when: >
    nfs_clients_cnpem_sirius_subnet is not defined or
    nfs_clients_cnpem_sirius_subnet | length == 0

- name: Check if NFS FAC workstation variable is set
  fail:
    msg: fac_workstation_ip variable is not set or empty!
  when: >
    fac_workstation_ip is not defined or
    fac_workstation_ip | length == 0

# Include Tasks

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-packages.yml
