---
__desktop_packages:
  - "rdesktop={{ pkg_version_rdesktop }}"
  - "htop={{ pkg_version_htop }}"
  - "vim={{ pkg_version_vim }}"
  - "ipython3={{ pkg_version_ipython3 }}"
  - "remmina={{ pkg_version_remmina }}"
  - "remmina-plugin-rdp={{ pkg_version_remmina_plugin_rdp }}"
  - "remmina-plugin-secret={{ pkg_version_remmina_plugin_secret }}"
  - "tightvncserver={{ pkg_version_tightvncserver }}"
  - "gvncviewer={{ pkg_version_gvncviewer }}*"
  - "xfce4={{ pkg_version_xfce4 }}"
  - "xfce4-goodies={{ pkg_version_xfce4_goodies }}"
  - "wmctrl={{ pkg_version_wmctrl }}"
  - "cups={{ pkg_version_cups }}"
  - "ca-certificates={{ pkg_version_ca_certificates }}"
  - "gconf2={{ pkg_version_gconf2 }}"
  - "libasound2={{ pkg_version_libasound2 }}"
  - "libgtk2.0-0={{ pkg_version_libgtk2_0_0 }}"
  - "libxss1={{ pkg_version_libxss1 }}"
  - "libffi6={{ pkg_version_libffi6 }}"
  - "libffi-dev={{ pkg_version_libffi_dev }}"
  - "libfreetype6={{ pkg_version_libfreetype6 }}"
  - "libfreetype6-dev={{ pkg_version_libfreetype6_dev }}"
  - "nmap={{ pkg_version_nmap }}"
  - "sshpass={{ pkg_version_sshpass }}"
  - "wait-for-it={{ pkg_version_wait_for_it }}"
  - "libgsl2={{ pkg_version_libgsl2 }}"
  - "libgsl-dev={{ pkg_version_libgsl_dev }}"
  - texlive-latex-recommended={{ pkg_version_texlive_latex_recommended }}
  - dvipng={{ pkg_version_dvipng }}
  - ghostscript={{ pkg_version_ghostscript }}

__desktop_pip_packages:
  - "python-nmap=={{ pkg_version_python_nmap }}"
  - "wakeonlan=={{ pkg_version_wakeonlan }}"
  - "requests=={{ pkg_version_requests }}"
  - "pyqtgraph=={{ pkg_version_pyqtgraph }}"
  - "pandas=={{ pkg_version_pandas }}"
  - "psutil=={{ pkg_version_psutil }}"
  - "termcolor=={{ pkg_version_termcolor }}"
  - "sh=={{ pkg_version_sh }}"
  - "cairocffi=={{ pkg_version_cairocffi }}"
  - "matplotlib=={{ pkg_version_matplotlib }}"
  - "scipy=={{ pkg_version_scipy }}"
  - "jupyter=={{ pkg_version_jupyter }}"
  - "xlrd=={{ pkg_version_xlrd }}"

__pip_executable: pip-sirius
