---
- name: Converge
  hosts: all

  vars:
    # Select whether to install recommended apps.
    pydm_recommended_apps_pip_install: true

  pre_tasks:
    - name: Include molecule overrides
      include_vars: "{{ lookup('first_found', possible_var_files) }}"
      vars:
        possible_var_files:
          - "../../../../group_vars/molecule_overrides.yml"

  roles:
    - role: lnls-ans-role-pydm
