---
- name: Converge
  hosts: all

  vars:
    # Select which categories to install. Remove
    # OPI categoty as it's a private repo
    sirius_apps_hlacons_install_categories:
      - sirius_apps_hlacons

  roles:
    - role: lnls-ans-role-sirius-hlacons
