---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
    group_vars:
      default_group:
  options:
    extra_vars:
      python_src_download_pkg_name: "Python-{{ python_src_version }}"
      python_src_download_url: "https://www.python.org/ftp/python/{{ python_src_version }}/{{ python_src_download_pkg_name }}.tgz"
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
platforms:
  - name: lnls-ans-role-python-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
