---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
    group_vars:
      default_group:
  options:
    extra-vars:
      csstudio_repository: production
      csstudio_base_url: "https://artifactory.esss.lu.se/artifactory/CS-Studio/{{ csstudio_repository }}"
      csstudio_archive: "{{ csstudio_base_url }}/cs-studio-ess-{{ csstudio_version }}-linux.gtk.x86_64.tar.gz"
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
platforms:
  - name: lnls-ans-role-cs-studio-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
