---
# package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_apps_packages_state: present

# PIP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_apps_pip_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
sirius_apps_install_recommends: true

# Sirius BPM tests path
sirius_apps_bpm_tests_dir: /usr/local/share/bpm-tests

# Groups of packages
# Example
#
# sirius_apps_packages_group_1:
#   - name: Math Phys
#     org_url: https://github.com/lnls-fac
#     repo_name: mathphys
#     repo_version: master
#     clone_path: /tmp
#     install_via_makefile: true
#     force_version: true
#
# sirius_apps_packages_group_2:
#   - name: Machine Applications
#     org_url: https://github.com/lnls-sirius
#     repo_name: machine-applications
#     repo_version: master
#     clone_path: /tmp
#     install_via_makefile: true
#     force_version: true
#
# sirius_apps_install_categories:
#   - sirius_apps_packages_group_1
#   - sirius_apps_packages_group_2
#
sirius_apps_packages_group_1: []

sirius_apps_packages_group_2: []

# Select which categories to install
sirius_apps_install_categories:
  - sirius_apps_packages_group_1
  - sirius_apps_packages_group_2

sirius_apps_config_files:
  - name: Sirius Apps environment variables
    filename: sirius_apps.sh
    pathname: "/etc/profile.d"

  - name: Sirius scripts environment variables
    filename: sirius_scripts.sh
    pathname: "/etc/profile.d"
