---
- name: Restart NFS server systemd service
  block:
    - name: Restart NFS server systemd service
      systemd:
        name: nfs-kernel-server
        state: restarted
  become: true
  ignore_errors: "{{ nfs_ignore_systemd_errors }}"
  rescue:
    - name: Show warning to user if systemd fails
      pause:
        seconds: 1
        echo: false
        prompt: "Could not reload NFS systemd service. Probably running in Docker? Continuing anyway ..."
