---
- name: Clone and Install Applications
  include_tasks: clone-install-app.yml
  with_items:
    - "{{ sirius_apps }}"
  when:
    - sirius_apps is defined and
      sirius_apps | length > 0

- name: Ensure Sirius Apps environment is installed
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.pathname }}/{{ item.filename }}"
    owner: root
    group: root
    force: true
    mode: 0644
  become: true
  with_items:
    - "{{ sirius_apps_config_files }}"
  when:
    - sirius_apps is defined and
      sirius_apps | length > 0
