---
- name: "Ensure repository {{ item.repo_name }} is cloned"
  git:
    repo: "{{ item.org_url }}/{{ item.repo_name }}"
    dest: "{{ item.clone_path }}/{{ item.repo_name }}"
    version: "{{ item.repo_version | default('master') }}"
    accept_hostkey: "{{ item.git_accept_hostkey | default(omit) }}"
    ssh_opts: "{{ item.git_ssh_opts | default(omit) }}"
    force: "{{ item.force_version | default(false) }}"

- name: "Install app at 'cons' Conda env"
  executable: /bin/bash
  shell: >
      source /opt/conda/etc/profile.d/conda.sh &&
      conda activate cons &&
      cd "{{ item.clone_path }}/{{ item.repo_name }}" &&
      pip install .

          
