---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Define NFS client packages
  set_fact:
    nfs_client_packages: "{{ __nfs_client_packages | default ([]) }}"
  when: nfs_client_packages is not defined

# Include Tasks

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-packages.yml

- name: Create symbolic link to lnls-ansible
  file:
    src: "/home/sirius/repos/lnls-ansible"
    dest: "/home/sirius/lnls-ansible"
    state: link
  become: true

