---
__epics_packages:
  - epics-dev={{ pkg_version_epics_dev }}
  - epics-pcas-dev={{ pkg_version_epics_pcas_dev }}
  - epics-extensions-dev

__sirius_apps_epics_pip_packages:

__python_executable: python-sirius

__pip_executable: pip-sirius
