---
- name: Converge
  hosts: all

  vars:
    nfs_server_control_room: 127.0.0.1
    nfs_server_control_opi: 127.0.0.1
    nfs_ignore_systemd_errors: true

  roles:
    - role: lnls-ans-role-nfsclient
