---
- name: Define Python executable
  set_fact:
    python_executable: "{{ __python_executable | default('python') }}"
  when: python_executable is not defined

- name: Define PIP executable
  set_fact:
    pip_executable: "{{ __pip_executable | default(omit) }}"
  when: pip_executable is not defined

- name: Define conda executable path
  set_fact:
    conda_executable: "{{ __conda_executable | default('/opt/conda/bin/conda') }}"
  when: conda_executable is not defined

- name: Define conda profile path
  set_fact:
    conda_profile: "{{ __conda_profile | default('/opt/conda/etc/profile.d/conda.sh') }}"
  when: conda_profile is not defined

- name: Define conda PIP packages
  set_fact:
    sirius_apps_hlacon_pip_dep_packages: "{{ __sirius_apps_hlacon_pip_dep_packages | default([]) }}"
  when: sirius_apps_hlacon_pip_dep_packages is not defined

- name: Define conda PIP packages state
  set_fact:
    sirius_apps_hlacon_pip_dep_packages_state: "{{ __sirius_apps_hlacon_pip_dep_packages_state | default(present) }}"
  when: sirius_apps_hlacon_pip_dep_packages_state is not defined

- name: Create cons environment
  conda:
    name: python
    version: "{{ sirius_apps_hlacon_conda_python_version }}"
    environment: "{{ sirius_apps_hlacon_conda_environment_path }}"
    state: present
    executable: "{{ conda_executable }}"

- name: Install conda dependencies
  conda:
    name:
      - "{{ item.name }}=={{ item.version }}"
    channels: conda-forge
    environment: "{{ sirius_apps_hlacon_conda_environment_path }}"
    state: present
    executable: "{{ conda_executable }}"
  with_items:
    - "{{ sirius_apps_hlacon_conda_packages }}"

- name: Install conda dependency PIP packages
  pip:
    name: "{{ sirius_apps_hlacon_pip_dep_packages }}"
    state: "{{ sirius_apps_hlacon_pip_dep_packages_state }}"
    executable: "{{ pip_executable | default(omit) }}"
  become: true

- name: Clone and install pip packages within cons conda environment
  pip:
    name: "{{ item.name }}=={{ item.version }}"
    state: present
    executable: "{{ sirius_apps_hlacon_conda_environment_path }}/bin/pip"
  with_items:
    - "{{ sirius_apps_hlacon_pip_packages }}"

- name: Create siriushlacon shell executables
  template:
    src: siriushlacon.j2
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
      - "{{ sirius_apps_hlacon_executables }}"
