---
- name: Define Repository keys
  set_fact:
    conda_rpm_keys: "{{ __conda_rpm_keys | list }}"
  when: conda_rpm_keys is not defined

- name: Define yum repositories
  set_fact:
    conda_yum_repositories: "{{ __conda_yum_repositories | list }}"
  when: conda_yum_repositories is not defined

- name: Define yum packages
  set_fact:
    conda_yum_packages: "{{ __conda_yum_packages | list }}"
  when: conda_yum_packages is not defined

- name: Conda RPM Keys
  rpm_key:
    state: present
    key: "{{ item.url }}"
  with_items: "{{ conda_rpm_keys }}"

- name: Conda Repositories
  yum_repository:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    baseurl: "{{ item.baseurl }}"
  with_items: "{{ conda_yum_repositories }}"

- name: Conda packages
  yum:
    name: "{{ item.package }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items: "{{ conda_yum_packages }}"

