---
- name: Converge
  hosts: all

  vars:
    # Select which categories to install. Remove
    # OPI categoty as it's a private repo
    sirius_apps_hla_install_categories:
      - sirius_apps_hla
      - sirius_apps_opis

  roles:
    - role: lnls-ans-role-sirius-hla
