---
- name: Converge
  hosts: all

  vars:
    epics7_base_url: "https://epics.anl.gov/download/base"
    epics7_base_archive: "{{ epics7_base_url }}/base-{{ epics7_base_version }}.tar.gz"

  roles:
    - role: lnls-ans-role-epics7
