---
__sirius_apps_packages:
  - "edm-dev={{ pkg_version_edm_dev }}"
  - "xpra={{ pkg_version_xpra }}"
  - "xvfb={{ pkg_version_xvfb }}"

__sirius_apps_pip_packages:
  - "QtAwesome=={{ pkg_version_qtawesome }}"

__python_executable: python-sirius

__pip_executable: pip-sirius
