---
# Delete pinning files if this repo is providing one
- name: Delete APT pinning configuration
  file:
    path: "{{ item.pathname }}/{{ item.filename }}"
    state: absent
  when: apt_deb_repo_enable_pinning
  with_items:
    - "{{ apt_pinning_paths }}"
  become: true
