---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: lnls-ans-role-visual-studio-code-opensuse
    image: opensuse/leap:15.1
    dockerfile: ../default/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ../code-only/playbook.yml
  inventory:
    links:
      group_vars: ../../../../group_vars/
verifier:
  name: testinfra
