---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ansible-role-visual-studio-code-centos
    image: centos:7
    dockerfile: ../default/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ../code-only/playbook.yml
verifier:
  name: testinfra
  directory: ../code-only/tests
