---
- name: Converge
  hosts: all

  vars:
    # Select which categories to install. Remove
    # OPI categoty as it's a private repo
    sirius_apps_install_categories:
      - sirius_apps_dev_packages
      - sirius_apps_iocs
      - sirius_apps_mgmt

  pre_tasks:
    - name: Include molecule overrides
      include_vars: "{{ lookup('first_found', possible_var_files) }}"
      vars:
        possible_var_files:
          - "../../../../group_vars/molecule_overrides.yml"

  roles:
    - role: lnls-ans-role-sirius-apps
