---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
    group_vars:
      default_group:
  options:
    extra-vars:
      phoebus_base_url: "https://controlssoftware.sns.ornl.gov/css_phoebus"
      phoebus_archive: "{{ phoebus_base_url }}/phoebus-{{ phoebus_version }}-linux.zip"
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
platforms:
  - name: lnls-ans-role-phoebus-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
