name: Merge Upstream
on:
  schedule:
    # scheduled for every night at midnight
    - cron: '0 0 * * *'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge master branch into travis-build for triggering CI.
        run: |
          git branch --all
          git config --list
          git checkout travis-build
          git merge --no-ff origin/master
          git push origin travis-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
